#if defined(RISCV32)
# define ARCH_TIMESIZE 64
# define HAVE_ARCH_TIME32_SYSCALLS 0
# define HAVE_ARCH_OLD_TIME64_SYSCALLS 0
# define PERSONALITY0_AUDIT_ARCH { AUDIT_ARCH_RISCV32, 0 }
#else
# define PERSONALITY0_AUDIT_ARCH { AUDIT_ARCH_RISCV64, 0 }
#endif
